server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/hms_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false

jwt:
  secret: my-super-secret-key-for-hms-project-123456
  expiration: 36000000